title: rrunix
description: Personal website - Teaching and Research
url: "https://rrunix.es"
baseurl: ""

# Build settings
markdown: kramdown

# Collections
collections_dir: .

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md
